#
# Module manifest for module 'WindowsServices'
#
# Generated by: Igor Macedo
#
# Generated on: 14/03/2018
#

@{
	ModuleVersion = '1.0'
	GUID = 'c6f36780-f7ea-4a94-826c-334747fcff88'
	Author = 'Igor Macedo'
	Description = 'Funções para auxiliar na geração de custom patches do Oracle EBS.'
	PowerShellVersion = '3.0'  
	RootModule = "WindowsServices"
	DefaultCommandPrefix = 'WindowsServices'
}